services:
  - type: web
    name: road-runner-moto
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: roadrunner_db
      - key: ADMIN_USER
        value: roadrunner
      - key: ADMIN_PASSWORD
        value: runner2026
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NUXT_PUBLIC_SITE_URL
        value: https://road-runner-moto.onrender.com
      - key: NUXT_PUBLIC_API_BASE
        value: https://road-runner-moto.onrender.com
